# configuration sample

graphite:
  host: 192.168.1.62
  port: 2003
  prefix: uptime.esp8266
timeout: 30
user_agent: uptime
checks:
  - host: http://temperature-relay.local
    path: /health
    interval: 5
#  - host: http://shutter-control.local
#    path: /health
#    interval: 5
#  - host: http://neopixel-control.local
#    path: /health
#    interval: 5

